flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint

from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('home.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template, abort, request
from flask_login import login_required, current_user

from flaskblog import db
from flaskblog.models import Post, User
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New post')


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post has been updated!')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted!')
    return redirect(url_for('main.home'))


@posts.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('user_post.html', posts=posts, user=user)

flaskblog/users/routes.py
import os

from flask import Blueprint, redirect, flash, render_template, url_for, request, current_app
from flask_login import current_user, login_user, logout_user, login_required

from flaskblog import bcrypt, db
from flaskblog.models import User
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(f'{form.password.data}').decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}!, You're can login")
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect('home')
        flash('Login unseccsfly pls check pass or email')
    return render_template('login.html', title='login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_pic = current_user.image_file
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            if old_pic != 'default.jpg':
                os.remove(os.path.join(current_app.root_path, 'static/profile_pics', old_pic))
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='account', image_file=image_file, form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<string:token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid/expired token')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(f'{form.password.data}').decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash("Password has been updated!, You're can login")
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    {% with messages = get_flash_messages %}
        {% for message in messages %}
            <div>{{ message }}</div>
        {% endfor %}
    {% endwith %}
    <h1>{{ current_user.username }}</h1>
    <h1>{{ current_user.email }}</h1>
    <img src="{{ image_file }}" alt="" height="300px" width="300px">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ form.username.label() }}
        {{ form.username }} <br>
        {% if form.username.errors %}
            {%for error in form.username.errors%}
                <div style="color:red;" >
                    {{error}}
                </div>
            {% endfor %}
        {% endif %}
        {{ form.email.label() }}
        {{ form.email }} <br>
        {% if form.email.errors %}
            {%for error in form.email.errors%}
                <div style="color:red;">
                    {{error}}
                </div>
            {% endfor %}
        {% endif %}
        {{ form.picture.label() }}
        {{ form.picture }} </br>
        {% if form.picture.errors %}
            {%for error in form.picture.errors%}
                <div style="color:red;" >
                    {{error}}
                </div>
            {% endfor %}
        {% endif %}
        {{ form.submit() }}
    </form>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div>
    <h1>{{ legend }}</h1>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.title.label() }}
        {{ form.title }} <br>
        {% if form.title.errors %}
            {%for error in form.title.errors%}
                <div style="color:red;">
                    {{error}}
                </div>
            {% endfor %}
        {% endif %}
        {{ form.content.label() }}
        {{ form.content }} <br>
        {% if form.content.errors %}
            {%for error in form.content.errors%}
                <div style="color:red;">
                    {{error}}
                </div>
            {% endfor %}
        {% endif %}
        {{ form.submit() }}
    </form>
    </div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article style="border: 1px solid black">
          <img height="100px" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"></img>
          <div>
            <div>
              <a href=" {{ url_for('posts.user_posts', username=post.author.username) }} ">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
            <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p>{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <a href="{{ url_for('main.home', page=page_num) }}" style="color:red;">{{ page_num }}</a>
            {% else %}
            <a href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <a href="{{ url_for('main.home') }}">home</a>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('posts.new_post') }}">new post</a>
    <a href="{{ url_for('users.account') }}">account</a>
    <a href="{{ url_for('users.logout') }}">logout</a>
    {% else %}
    <a href="{{ url_for('users.login') }}">login</a>
    <a href="{{ url_for('users.register') }}">register</a>
    {% endif %}
    <a href="{{ url_for('main.about') }}">about</a>
    {% with messages = get_flashed_messages() %}
        {% for message in messages %}
            <div style="color:red;">{{ message }}</div>
        {% endfor %}
    {% endwith %}
    {% block content %}
    {% endblock content %}
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.email.label() }}
            {{ form.email }} <br>
            {% if form.email.errors %}
                {%for error in form.email.errors%}
                    <div style="color:red;">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.password.label() }}
            {{ form.password }} <br>
            {% if form.password.errors %}
                {%for error in form.password.errors%}
                    <div style="color:red;">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.remember.label }}
            {{ form.remember }} <br>
            <a href="{{ url_for('users.reset_request') }}">Forgot password?</a> <br>
            {{ form.submit() }}
        </form>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article style="border: 1px solid black">
  <img height="100px" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"></img>
  <div>
    <div>
      <a href=" {{ url_for('posts.user_posts', username=post.author.username) }} ">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
      {% if post.author == current_user %}
        <a href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
        <form method="POST" action="{{ url_for('posts.delete_post', post_id=post.id) }}"> <button type="submit" style="color:red;">Delete</button> </form>

      {% endif %}
    </div>
    <h2>{{ post.title }}</h2>
    <p>{{ post.content }}</p>
  </div>
</article>
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.username.label() }}
            {{ form.username }} <br>
            {% if form.username.errors %}
                {%for error in form.username.errors%}
                    <div style="color:red;" >
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.email.label() }}
            {{ form.email }} <br>
            {% if form.email.errors %}
                {%for error in form.email.errors%}
                    <div style="color:red;">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.password.label() }}
            {{ form.password }} <br>
            {% if form.password.errors %}
                {%for error in form.password.errors%}
                    <div style="color:red;">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.confirm_password.label() }}
            {{ form.confirm_password }} <br>
            {% if form.confirm_password.errors %}
                {%for error in form.confirm_password.errors%}
                    <div style="color:red;">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.submit() }}
        </form>
    </div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.email.label() }}
            {{ form.email }} <br>
            {% if form.email.errors %}
                {%for error in form.email.errors%}
                    <div style="color:red;">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.submit() }}
        </form>
    </div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.password.label() }}
            {{ form.password }} <br>
            {% if form.password.errors %}
                {%for error in form.password.errors%}
                    <div style="color:red;">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.confirm_password.label() }}
            {{ form.confirm_password }} <br>
            {% if form.confirm_password.errors %}
                {%for error in form.confirm_password.errors%}
                    <div style="color:red;">
                        {{error}}
                    </div>
                {% endfor %}
            {% endif %}
            {{ form.submit() }}
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_post.html
{% extends "layout.html" %}
{% block content %}
    <h1>Posts by {{ user.username }} ( {{ posts.total }} )</h1>
    {% for post in posts.items %}
        <article style="border: 1px solid black">
          <img height="100px" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"></img>
          <div>
            <div>
              <a href=" {{ url_for('posts.user_posts', username=post.author.username) }} ">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
            <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p>{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <a href="{{ url_for('posts.user_posts', page=page_num, username=user.username) }}" style="color:red">{{ page_num }}</a>
            {% else %}
            <a href="{{ url_for('posts.user_posts', page=page_num, username=user.username) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}